services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      USE_FASTIFY: ${USE_FASTIFY}
    volumes:
      - ./src:/app/src
      - logs:/app/logs
      - uploads:/app/uploads
    networks:
      - koa-network
    restart: on-failure
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - koa-network
    restart: always
volumes:
  logs:
  uploads:
  database:
networks:
  koa-network:
    driver: bridge
