version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - koa-network
    depends_on:
      - postgres
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment:
      - ${PORT}
    volumes:
      - ./src:/home/node/app/src
      - logs:/home/node/app/logs
    restart: on-failure
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    networks:
      - koa-network
    ports:
      - ${POSTGRES_PORT}-${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: on-failure
volumes:
  logs:
networks:
  koa-network:
    driver: bridge
